# Generated by Django 4.2.10 on 2024-02-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('start_range', models.BigIntegerField()),
                ('end_range', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telecom.operator')),
            ],
            options={
                'unique_together': {('code', 'start_range', 'end_range')},
            },
        ),
    ]
