# Generated by Django 4.2.10 on 2024-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='region',
            field=models.TextField(),
        ),
    ]
